local function setup()
	require("nvim-treesitter.configs").setup({
		ensure_installed = {
			"bash",
			"cmake",
			"comment",
			"css",
			"csv",
			"diff",
			"dockerfile",
			"editorconfig",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"glimmer_javascript",
			"glimmer_typescript",
			"html",
			"java",
			"javascript",
			"jsdoc",
			"json",
			"jsonc",
			"lua",
			"luadoc",
			"make",
			"markdown",
			"markdown_inline",
			"proto",
			"python",
			"regex",
			"ruby",
			"rust",
			"sql",
			"ssh_config",
			"terraform",
			"toml",
			"typescript",
			"vim",
			"xml",
			"yaml",
		},
		highlight = { enable = true },
		playground = { enable = true },
		endwise = { enable = true },
		incremental_selection = {
			enable = true,
			keymaps = {
				node_incremental = "<enter>",
				scope_incremental = "+",
				node_decremental = "-",
			},
		},
	})
end

return {
	{
		dir = vim.fn.stdpath("config") .. "/lua/plugins/treesitter",
		dependencies = {
			{ import = "plugins.treesitter.treesitter" },
			{ import = "plugins.treesitter.autopairs" },
		},
		config = setup,
	},
}
